# Generated by Django 5.1.1 on 2026-05-08 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(blank=True, null=True)),
                ('attendance_count', models.IntegerField(default=0)),
                ('today_attended', models.BooleanField(default=False)),
                ('chap', models.IntegerField(default=0)),
                ('gold', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
