# Generated by Django 5.1.1 on 2026-05-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_charinfo_exp_remove_charinfo_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='charinfo',
            name='last_explore_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
