# Generated by Django 5.1.1 on 2026-05-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_charinfo_last_explore_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='charinfo',
            name='last_explore_map_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charinfo',
            name='last_explore_node_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
