# Generated by Django 5.1.1 on 2026-05-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kr', models.CharField(max_length=50, verbose_name='이름 (한글)')),
                ('name_en', models.CharField(max_length=100, verbose_name='이름 (영문)')),
                ('catchphrase', models.CharField(max_length=100, verbose_name='캐치프레이즈')),
                ('quote', models.CharField(max_length=100, verbose_name='한마디')),
                ('origin', models.CharField(max_length=50, verbose_name='출신지')),
                ('gender', models.CharField(max_length=20, verbose_name='성별')),
                ('age', models.CharField(max_length=30, verbose_name='나이')),
                ('race', models.CharField(max_length=30, verbose_name='종족')),
                ('animal_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='동물 객체 (수인의 경우)')),
                ('height', models.CharField(max_length=30, verbose_name='신장')),
                ('weight', models.CharField(max_length=30, verbose_name='체중')),
                ('keyword1', models.CharField(max_length=20, verbose_name='성격 키워드 1')),
                ('keyword2', models.CharField(max_length=20, verbose_name='성격 키워드 2')),
                ('keyword3', models.CharField(max_length=20, verbose_name='성격 키워드 3')),
                ('appearance', models.TextField(verbose_name='외관 서술')),
                ('personality', models.TextField(verbose_name='성격 서술')),
                ('other_info', models.TextField(verbose_name='특징 서술')),
                ('stat_str', models.PositiveIntegerField(default=0, verbose_name='근력')),
                ('stat_agi', models.PositiveIntegerField(default=0, verbose_name='민첩')),
                ('stat_int', models.PositiveIntegerField(default=0, verbose_name='지능')),
                ('stat_luk', models.PositiveIntegerField(default=0, verbose_name='행운')),
                ('stat_rep', models.PositiveIntegerField(default=0, verbose_name='평판')),
                ('stat_good', models.PositiveIntegerField(default=0, verbose_name='선의')),
                ('stat_mag', models.PositiveIntegerField(default=0, verbose_name='마력')),
                ('stat_div', models.PositiveIntegerField(default=0, verbose_name='신성력')),
            ],
            options={
                'verbose_name': '캐릭터',
            },
        ),
    ]
