# Generated by Django 5.1.1 on 2026-05-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='energy',
            field=models.IntegerField(default=100, verbose_name='활력'),
        ),
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=100, verbose_name='골드'),
        ),
    ]
