# Generated by Django 5.1.1 on 2026-05-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_character_energy_character_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='points',
            field=models.PositiveIntegerField(default=30, verbose_name='용사기여도'),
        ),
    ]
