# Generated by Django 5.1.1 on 2026-06-07 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_character_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='타이틀명')),
            ],
            options={
                'verbose_name': '타이틀',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.title', verbose_name='현재 타이틀'),
        ),
        migrations.AddField(
            model_name='character',
            name='unlocked_titles',
            field=models.ManyToManyField(blank=True, related_name='characters', to='member.title', verbose_name='보유 타이틀'),
        ),
    ]
