# Generated by Django 5.1.1 on 2026-05-08 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='아이템명')),
                ('category', models.CharField(choices=[('ESSENCE', '정수'), ('FOOD', '음식'), ('CONSUMABLE', '소모품'), ('EQUIPMENT', '소지품'), ('SPECIAL', '특수 아이템')], max_length=20, verbose_name='종류')),
                ('description', models.TextField(verbose_name='설명')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격(G)')),
                ('is_sellable', models.BooleanField(default=False, verbose_name='상점 판매 여부')),
                ('is_investigation_reward', models.BooleanField(default=False, verbose_name='조사 보상 여부')),
                ('is_craft_result', models.BooleanField(default=False, verbose_name='조합 결과물 여부')),
                ('origin', models.CharField(blank=True, max_length=50, null=True, verbose_name='특산품 출처')),
                ('effect_type', models.CharField(choices=[('NONE', '효과 없음'), ('CONTRIBUTION_UP', '용사 기여도 증가'), ('CONTRIBUTION_DOWN', '용사 기여도 감소'), ('HP_RECOVERY', '체력 회복')], default='NONE', max_length=30, verbose_name='특수 효과 종류')),
                ('effect_value', models.IntegerField(default=0, verbose_name='특수 효과 수치')),
            ],
            options={
                'verbose_name': '아이템',
                'verbose_name_plural': '아이템 목록',
            },
        ),
        migrations.CreateModel(
            name='GiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('message', models.TextField(blank=True, null=True, verbose_name='메시지')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명 여부')),
                ('is_read', models.BooleanField(default=False, verbose_name='수신 확인')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='보낸 시간')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to='member.character', verbose_name='받는 캐릭터')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gifts', to=settings.AUTH_USER_MODEL, verbose_name='보낸 사람')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='선물 아이템')),
            ],
            options={
                'verbose_name': '선물 기록',
                'verbose_name_plural': '선물 기록 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 변동일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL, verbose_name='플레이어')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='보유 아이템')),
            ],
            options={
                'verbose_name': '인벤토리',
                'verbose_name_plural': '인벤토리 목록',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
