# Generated by Django 5.1.1 on 2026-05-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100, unique=True, verbose_name='결과물 이름')),
                ('recipe', models.TextField(help_text="예시: ['재료1', '재료2']", verbose_name='조합 재료 목록')),
                ('discovered', models.BooleanField(default=False, verbose_name='최초 발견 여부')),
                ('discoverer', models.CharField(blank=True, max_length=100, null=True, verbose_name='최초 발견자')),
            ],
        ),
    ]
