# Generated by Django 5.1.1 on 2026-05-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='material1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='재료1'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='material2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='재료2'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='material3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='재료3'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='material4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='재료4'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='itemName',
            field=models.CharField(max_length=100, unique=True, verbose_name='아이템'),
        ),
    ]
