# Generated by Django 5.1.1 on 2026-05-09 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_recipe_recipe_recipe_category_recipe_desc_and_more'),
        ('member', '0002_character_energy_character_gold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('message', models.TextField(blank=True, null=True, verbose_name='메시지')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='받은 날짜')),
                ('is_claimed', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to='member.character')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GiftLog',
        ),
    ]
