# Generated by Django 5.1.1 on 2026-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gift_delete_giftlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ESSENCE', '정수'), ('FOOD', '음식'), ('CONSUMABLE', '소모품'), ('EQUIPMENT', '소지품'), ('SPECIAL', '특수 아이템'), ('ORGANIC', '유기재료'), ('MINERAL', '광물'), ('CLOTHES', '옷'), ('JEWELRY', '장신구'), ('NORMAL', '일반재료')], max_length=20, verbose_name='종류'),
        ),
    ]
