# Generated by Django 5.1.1 on 2026-05-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100, verbose_name='레시피 이름')),
                ('hint', models.TextField(verbose_name='힌트')),
                ('item_name', models.CharField(max_length=100, verbose_name='아이템 이름')),
            ],
            options={
                'verbose_name': '레시피 힌트',
            },
        ),
    ]
