# Generated by Django 5.1.1 on 2026-05-31 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recipehint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipehint',
            name='item_name',
        ),
        migrations.AddField(
            model_name='recipehint',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.item', verbose_name='연결 아이템'),
        ),
    ]
