# Generated by Django 5.1.1 on 2026-05-31 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_recipehint_item_name_recipehint_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipehint',
            options={},
        ),
        migrations.AlterField(
            model_name='recipehint',
            name='hint',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipehint',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.item'),
        ),
        migrations.AlterField(
            model_name='recipehint',
            name='recipe_name',
            field=models.CharField(max_length=100),
        ),
    ]
